version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - 6379:6379
      - 16379:16379
    environment:
      # - 'REDIS_PASSWORD=bitnami'
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      # - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    ports:
      - 6380:6379
      - 16380:16379
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      # - 'REDIS_PASSWORD=bitnami'
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      # - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    ports:
      - 6381:6379
      - 16381:16379
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      # - 'REDIS_PASSWORD=bitnami'
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      # - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    ports:
      - 6382:6379
      - 16382:16379
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      # - 'REDIS_PASSWORD=bitnami'
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    ports:
      - 6383:6379
      - 16383:16379
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      # - 'REDIS_PASSWORD=bitnami'
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    ports:
      - 6384:6379
      - 16384:16379
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    environment:
      # - 'REDIS_PASSWORD=bitnami'
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      # - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      # - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
