version: '2'

services:
  # proxy:
    # image: flant/redis-sentinel-proxy
    # ports:
    #   - 9999:9999
    # command: -listen :9999 -master mymaster -sentinel redis-sentinel:26379
    # depends_on:
    #   - redis-sentinel
  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:6.0-debian-10
    volumes:
      - ./data/sentinel:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis
    ports:
      - 26379:26379
    depends_on:
      - redis
      - redis-slave
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/master:/bitnami
    ports:
      - 6379:6379
  redis-slave:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/slave:/bitnami
    ports:
      - 6378:6379
    depends_on:
      - redis